on:
  repository_dispatch:
    types: [test_result]

jobs:
  show_params:
    runs-on: ubuntu-latest
    steps:
      - env:
          FIREBASESERVICEACCOUNT: ${{ secrets[github.event.client_payload.firebase_service_account] }}
          PROJECTID: ${{ secrets[github.event.client_payload.oriject_id] }}
          TARGET: ${{ secrets[github.event.client_payload.target] }}
      - run: echo $FIREBASESERVICEACCOUNT
      - run: echo $PROJECTID
      - run: echo $TARGET
