on:
  repository_dispatch:
    types: [test_result]

jobs:
  show_params:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.FIREBASE_SERVICE_ACCOUNT_UX_IUM }}
        run: echo $MESSAGE
